package net.dezilla.dectf2.util;

public enum CustomDamageCause {
	
	ENEMY_SPAWN,
	SPAWN_WITH_FLAG,
	FLAG_POISON,
	KIT_SWITCH,
	SHIELDED_DAMAGE,
	ARCHER_HEADSHOT,
	MEDIC_HEAL,
	NINJA_TELEPORT,
	MAGE_LIGHTNING,
	MAGE_BLOOD_LEACH;
}
